# Generated by Django 2.2.2 on 2019-06-10 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='category',
            field=models.ManyToManyField(to='users.Category'),
        ),
    ]
