# Generated by Django 2.2.2 on 2019-06-10 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='Event Name',
            new_name='name',
        ),
    ]
